### ISSUE TITLE
Update analytics doc 

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/docs-mg#16]
**Description:**

update the following section
https://mg.docs.wso2.com/en/latest/how-tos/analytics-for-microgateway/#generating-a-microgateway-usage-report
change it to generate reports in analytics dashboard instead of admin portal.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by TanyaM** [comment]
Architecture and How real-time publishing works sections of the doc is also not updated.

**Comment by TanyaM** [comment]
There are broken images under **Using real-time data publishing (gRPC-based)** section.

**Comment by TanyaM** [comment]
Priority changed as the doc is referenced from training materials

**Comment by AmaliMatharaarachchi** [comment]
@VirajSalaka Would you be able to check on adding architecture and how it works sections for GRPC analytics?
