### ISSUE TITLE
Requirement of a description of Backend JWT

### ISSUE THREAD

**Issue by HeshanSudarshana** [wso2/docs-mg#33]
### Description:
A description of Backend JWT should be added to the concepts section in order to provide a better understanding of the feature.
(Reference for the APIM doc - https://apim.docs.wso2.com/en/3.0.0/learn/api-gateway/passing-end-user-attributes-to-the-backend/passing-enduser-attributes-to-the-backend-using-jwt/#passing-enduser-attributes-to-the-backend-using-jwt)

**Comment by AmaliMatharaarachchi** [comment]
Closing as it is fixed with https://github.com/wso2/docs-mg/pull/10
