### ISSUE TITLE
320 about this release outof date

### ISSUE THREAD

**Issue by praminda** [wso2/docs-mg#45]
### Description:

About this release page has 310 release note content. Need to update with 320 release note.

### Content Positioning in Documentation:

- Link: https://mg.docs.wso2.com/en/latest/getting-started/about-this-release/#

- Heading (& Step):

- Any other reference:

**Comment by AmaliMatharaarachchi** [comment]
Fixed with https://github.com/wso2/docs-mg/pull/50
