### ISSUE TITLE
"Configuration for WSO2 API Manager" page under "Install and Setup" section has 3.1.0 content

### ISSUE THREAD

**Issue by TanyaM** [wso2/docs-mg#46]
### Description:
[Configuration for WSO2 API Manager](https://mg.docs.wso2.com/en/latest/install-and-setup/configuration-for-wso2-api-manager/#configuring-the-microgateway-31x-toolkit) has 3.1.0 content and has not been updated for 3.2.0 content. 

### Content Positioning in Documentation:

- Link:
https://mg.docs.wso2.com/en/latest/install-and-setup/configuration-for-wso2-api-manager/#configuring-the-microgateway-31x-toolkit

- Heading (& Step):
Install and Setup

**Comment by TanyaM** [comment]
Priority changed as the docs is referenced from training materials

**Comment by AmaliMatharaarachchi** [comment]
Fixed with https://github.com/wso2/docs-mg/pull/40/
