### ISSUE TITLE
Improve troubleshooting docs

### ISSUE THREAD

**Issue by AmaliMatharaarachchi** [wso2/docs-mg#66]
### Description:

Update/improve the list of error codes and responses and common exceptions.
https://mg.docs.wso2.com/en/latest/troubleshooting/troubleshooting/

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by praminda** [comment]
Shall we update the content in troubleshooting guides. Also How about restructuring the trblsht pages like this.
1. Common errors and exceptions.
1. Runtime error codes and responses
1. Debug logs
