### ISSUE TITLE
Documentation still refers to Balx

### ISSUE THREAD

**Issue by nirmal070125** [wso2/docs-mg#7]
**Description:**

https://docs.wso2.com/display/MG310/Using+an+OpenAPI+Definition#UsinganOpenAPIDefinition-Step1.2-Buildtheproject 

https://docs.wso2.com/display/MG310/Importing+a+Group+of+APIs+from+WSO2+API+Manager

Still says what is generated from build command of MGW toolkit is a balx, but if I'm not mistaken, it's a jar now and this is updated in https://docs.wso2.com/display/MG310/Importing+a+Single+API+from+WSO2+API+Manager

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
310

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by AmaliMatharaarachchi** [comment]
This needs to be corrected in both 3.1.0 doc space and 3.2.0 mkdocs.
