### ISSUE TITLE
Deploy in K8S configuration page should be updated.

### ISSUE THREAD

**Issue by menakaj** [wso2/docs-mg#73]
### Description:
1. In the k8s deployment configurations, an explanation should be added for each config section. ([kubernetes.kubernetesDeployment], [kubernetes.kubernetesService], .. etc)

2. Remove the kubernetesJobs section from the config docs as it is not relevant to Mgw.

3. Remove the namespace parameter from the config catalogue since it is not being used.

4. In [2], the generated directory structure is different. 
<img width="364" alt="Screenshot 2020-11-13 at 10 53 30" src="https://user-images.githubusercontent.com/10165411/99032035-84eb3680-259e-11eb-9aa1-926171f848ca.png">

https://mg.docs.wso2.com/en/latest/reference/configurations/deployment.toml-for-kubernetes/#kuberneteskubernetesdeployment
[2] https://mg.docs.wso2.com/en/latest/install-and-setup/install-on-kubernetes/#step-4-deploy-the-docker-image-in-a-kubernetes-environment

### Content Positioning in Documentation:

- Link:

- Heading (& Step):

- Any other reference:

---

**Comment by Rajith90** [comment]
fixed with : https://github.com/wso2/docs-mg/pull/135
